controller_manager:
  ros__parameters:
    use_sim_time: False
    update_rate: 400  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    gravity_compensation_controller:
        type: gravity_compensation_controller/GravityCompensationController

gravity_compensation_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    kinetic_friction_scalars:
      - 0.8
      - 0.8
      - 0.8
      - 0.1
    torque_scaling_factors:
      - 1.0
      - 1.0
      - 1.0
      - 1.0